@echo off
setlocal

cd /d "%~dp0"

for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') do set "SEDA_RUN_TIMESTAMP=%%i"
if not defined SEDA_MAGALU_BROWSER_PROFILE set "SEDA_MAGALU_BROWSER_PROFILE=C:/tmp/seda_magalu_profiles/run_magalu_casas_interleaved_ref_ldy_%SEDA_RUN_TIMESTAMP%"

rem Shared defaults for stable RDP full runs.
if not defined SEDA_POSTAL_CODE set SEDA_POSTAL_CODE=01001-001
if not defined SEDA_TIMEOUT set SEDA_TIMEOUT=25
if not defined SEDA_RETAILER_SWITCH_SLEEP_SECONDS set SEDA_RETAILER_SWITCH_SLEEP_SECONDS=0
set "SEDA_COMBINED_RETAILER_RUN=1"
set "SEDA_DB_REPLACE_RETAILER_BEFORE_LOAD="
set "SEDA_FORCE_DATED_RUN_ROOT=1"
set SEDA_RUN_ROOT=

rem Magalu defaults.
if not defined SEDA_MAGALU_FETCH_MODE set SEDA_MAGALU_FETCH_MODE=magalu_graphql_first
if not defined SEDA_MAGALU_LISTING_FETCH_MODE set SEDA_MAGALU_LISTING_FETCH_MODE=magalu_browser_zenrows
if not defined SEDA_MAGALU_LISTING_ALLOW_ZENROWS set SEDA_MAGALU_LISTING_ALLOW_ZENROWS=1
if not defined SEDA_MAGALU_DEFAULT_ALLOW_ZENROWS set SEDA_MAGALU_DEFAULT_ALLOW_ZENROWS=1
if not defined SEDA_MAGALU_DEFAULT_ZENROWS_DRY_RUN set SEDA_MAGALU_DEFAULT_ZENROWS_DRY_RUN=0
if not defined SEDA_MAGALU_ZENROWS_FIELD_FALLBACK set SEDA_MAGALU_ZENROWS_FIELD_FALLBACK=1
if not defined SEDA_MAGALU_ZENROWS_FIELD_PROFILE set SEDA_MAGALU_ZENROWS_FIELD_PROFILE=auto_custom_headers
if not defined SEDA_MAGALU_ZENROWS_FIELD_TIMEOUT set SEDA_MAGALU_ZENROWS_FIELD_TIMEOUT=90
if not defined SEDA_MAGALU_ZENROWS_FIELD_MAX_ITEMS set SEDA_MAGALU_ZENROWS_FIELD_MAX_ITEMS=25
if not defined SEDA_MAGALU_ZENROWS_FIELD_FAILURE_STREAK set SEDA_MAGALU_ZENROWS_FIELD_FAILURE_STREAK=3
if not defined SEDA_MAGALU_ZENROWS_FIELD_CHECKPOINT_EVERY set SEDA_MAGALU_ZENROWS_FIELD_CHECKPOINT_EVERY=5
if not defined SEDA_MAGALU_LISTING_ZENROWS_DRY_RUN set SEDA_MAGALU_LISTING_ZENROWS_DRY_RUN=0
if not defined SEDA_MAGALU_LISTING_ZENROWS_PROFILE set SEDA_MAGALU_LISTING_ZENROWS_PROFILE=premium_html
if not defined SEDA_MAGALU_LISTING_ZENROWS_TIMEOUT set SEDA_MAGALU_LISTING_ZENROWS_TIMEOUT=45
if not defined SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_PROFILES set SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_PROFILES=listing_next_data_js_wait
if not defined SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_SLEEP_SECONDS set SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_SLEEP_SECONDS=2
set SEDA_MAGALU_DETAIL_GRAPHQL=1
set SEDA_MAGALU_BROWSER_GRAPHQL=1
set SEDA_MAGALU_REVIEW_GRAPHQL=1
set SEDA_MAGALU_HTML_REQUESTS_FETCH=1
set SEDA_MAGALU_HTML_BROWSER_FALLBACK=0
set SEDA_MAGALU_PDP_NAV_FALLBACK=0
set SEDA_MAGALU_ZENROWS_DETAIL_FALLBACK=0
if not defined SEDA_MAGALU_ZENROWS_PDP_FALLBACK set SEDA_MAGALU_ZENROWS_PDP_FALLBACK=1
if not defined SEDA_MAGALU_ZENROWS_PDP_TIMEOUT set SEDA_MAGALU_ZENROWS_PDP_TIMEOUT=120
if not defined SEDA_MAGALU_LAST_KNOWN_DB_FALLBACK set SEDA_MAGALU_LAST_KNOWN_DB_FALLBACK=1
if not defined SEDA_MAGALU_LAST_KNOWN_HISTORY_LIMIT set SEDA_MAGALU_LAST_KNOWN_HISTORY_LIMIT=30
if not defined SEDA_MAGALU_LAST_KNOWN_DB_TIMEOUT_MS set SEDA_MAGALU_LAST_KNOWN_DB_TIMEOUT_MS=15000
if not defined SEDA_MAGALU_SEARCH_BROWSER_ATTEMPTS set SEDA_MAGALU_SEARCH_BROWSER_ATTEMPTS=1
if not defined SEDA_MAGALU_SEARCH_RETRIES set SEDA_MAGALU_SEARCH_RETRIES=0
if not defined SEDA_MAGALU_DETAIL_RETRIES set SEDA_MAGALU_DETAIL_RETRIES=0
if not defined SEDA_MAGALU_REVIEW_RETRIES set SEDA_MAGALU_REVIEW_RETRIES=0
if not defined SEDA_MAGALU_REVIEW_INITIAL_SLEEP_SECONDS set SEDA_MAGALU_REVIEW_INITIAL_SLEEP_SECONDS=0
if not defined SEDA_MAGALU_REVIEW_SLEEP_SECONDS set SEDA_MAGALU_REVIEW_SLEEP_SECONDS=0
if not defined SEDA_MAGALU_REVIEW_HTML_MAX_PAGES set SEDA_MAGALU_REVIEW_HTML_MAX_PAGES=10
if not defined SEDA_MAGALU_SHIPPING_BLANK_RETRY set SEDA_MAGALU_SHIPPING_BLANK_RETRY=0
if not defined SEDA_MAGALU_DETAIL_HTML_FALLBACK set SEDA_MAGALU_DETAIL_HTML_FALLBACK=0
if not defined SEDA_MAGALU_DETAIL_403_ABORT_THRESHOLD set SEDA_MAGALU_DETAIL_403_ABORT_THRESHOLD=5
if not defined SEDA_MAGALU_REVIEW_403_ABORT_THRESHOLD set SEDA_MAGALU_REVIEW_403_ABORT_THRESHOLD=5
if not defined SEDA_MAGALU_BROWSER_HTML_ATTEMPTS set SEDA_MAGALU_BROWSER_HTML_ATTEMPTS=1
if not defined SEDA_MAGALU_BROWSER_MAX_USES set SEDA_MAGALU_BROWSER_MAX_USES=50
if not defined SEDA_MAGALU_BROWSER_MAX_AGE_SECONDS set SEDA_MAGALU_BROWSER_MAX_AGE_SECONDS=1200
if not defined SEDA_MAGALU_BROWSER_RESTART_SLEEP_SECONDS set SEDA_MAGALU_BROWSER_RESTART_SLEEP_SECONDS=2
if not defined SEDA_MAGALU_BROWSER_CLOSE_ON_EXIT set SEDA_MAGALU_BROWSER_CLOSE_ON_EXIT=1
set SEDA_MAGALU_SEARCH_FALLBACK_PAGE_SIZES=

rem Casas Bahia direct API defaults.
if not defined SEDA_CASAS_BAHIA_FETCH_MODE set SEDA_CASAS_BAHIA_FETCH_MODE=graphql
if not defined SEDA_CASAS_BAHIA_DEFAULT_ALLOW_ZENROWS set SEDA_CASAS_BAHIA_DEFAULT_ALLOW_ZENROWS=1
if not defined SEDA_CASAS_BAHIA_DEFAULT_ZENROWS_DRY_RUN set SEDA_CASAS_BAHIA_DEFAULT_ZENROWS_DRY_RUN=0
if not defined SEDA_CASAS_BAHIA_PRODUCT_SOURCE_ZENROWS_RETRIES set SEDA_CASAS_BAHIA_PRODUCT_SOURCE_ZENROWS_RETRIES=0
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_FALLBACK set SEDA_CASAS_BAHIA_ZENROWS_FIELD_FALLBACK=1
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_PROFILE_10X set SEDA_CASAS_BAHIA_ZENROWS_FIELD_PROFILE_10X=premium_html
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_PROFILE_25X set SEDA_CASAS_BAHIA_ZENROWS_FIELD_PROFILE_25X=pdp_js_full
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_TIMEOUT set SEDA_CASAS_BAHIA_ZENROWS_FIELD_TIMEOUT=45
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_FAILURE_STREAK set SEDA_CASAS_BAHIA_ZENROWS_FIELD_FAILURE_STREAK=3
if not defined SEDA_CASAS_BAHIA_ZENROWS_FIELD_CHECKPOINT_EVERY set SEDA_CASAS_BAHIA_ZENROWS_FIELD_CHECKPOINT_EVERY=5
if not defined SEDA_CASAS_BAHIA_LAST_KNOWN_DB_FALLBACK set SEDA_CASAS_BAHIA_LAST_KNOWN_DB_FALLBACK=1
if not defined SEDA_CASAS_BAHIA_LAST_KNOWN_HISTORY_LIMIT set SEDA_CASAS_BAHIA_LAST_KNOWN_HISTORY_LIMIT=30
if not defined SEDA_CASAS_BAHIA_LAST_KNOWN_DB_TIMEOUT_MS set SEDA_CASAS_BAHIA_LAST_KNOWN_DB_TIMEOUT_MS=15000
if not defined SEDA_RETRY_SLEEP_SECONDS set SEDA_RETRY_SLEEP_SECONDS=0

call :run_magalu REF
if errorlevel 1 exit /b 1
call :sleep_between

call :run_casas REF
if errorlevel 1 exit /b 1
call :sleep_between

call :run_magalu LDY
if errorlevel 1 exit /b 1
call :sleep_between

call :run_casas LDY
if errorlevel 1 exit /b 1

echo [SEDA] Magalu/Casas Bahia interleaved REF/LDY full run completed
exit /b 0

:run_magalu
set "SEDA_RETAILERS=magalu"
set "SEDA_ACTIVE_RETAILER=magalu"
set "SEDA_RUN_ROOT="
set "SEDA_FETCH_MODE=%SEDA_MAGALU_FETCH_MODE%"
call :run_stage Magalu %~1 seda.magalu.magalu_orchestrator %~1
exit /b %errorlevel%

:run_casas
set "SEDA_RETAILERS=casas_bahia"
set "SEDA_ACTIVE_RETAILER=casas_bahia"
set "SEDA_RUN_ROOT="
set "SEDA_FETCH_MODE=%SEDA_CASAS_BAHIA_FETCH_MODE%"
call :run_stage "Casas Bahia" %~1 seda.casas_bahia.casas_bahia_orchestrator %~1
exit /b %errorlevel%

:run_stage
set "RETAILER_LABEL=%~1"
set "PRODUCT_LABEL=%~2"
set "MODULE_NAME=%~3"
set "PRODUCT_LINE=%~4"
set SEDA_RUN_ROOT=
echo [SEDA] %RETAILER_LABEL% %PRODUCT_LABEL% full run started
call python -m %MODULE_NAME% --product-line %PRODUCT_LINE% --all
if errorlevel 1 (
    echo [SEDA] %RETAILER_LABEL% %PRODUCT_LABEL% full run failed
    exit /b 1
)
echo [SEDA] %RETAILER_LABEL% %PRODUCT_LABEL% full run completed
exit /b 0

:sleep_between
if "%SEDA_RETAILER_SWITCH_SLEEP_SECONDS%"=="0" exit /b 0
echo [SEDA] waiting %SEDA_RETAILER_SWITCH_SLEEP_SECONDS% seconds before next retailer/product line
timeout /t %SEDA_RETAILER_SWITCH_SLEEP_SECONDS% /nobreak >nul
exit /b 0
