@echo off
setlocal
REM Run a single Magalu product line end-to-end. Usage: run_magalu_full.bat <TV|REF|LDY>
if "%~1"=="" (echo Usage: %~nx0 ^<TV^|REF^|LDY^> & exit /b 1)
set "SEDA_LINE=%~1"

cd /d "%~dp0"

if not exist "%~dp0seda\magalu\log" mkdir "%~dp0seda\magalu\log"
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') do set "SEDA_RUN_TIMESTAMP=%%i"
if not defined SEDA_RUN_LOG_FILE set "SEDA_RUN_LOG_FILE=%~dp0seda\magalu\log\magalu_%SEDA_LINE%_full_%SEDA_RUN_TIMESTAMP%.log"
if not defined PYTHONUNBUFFERED set PYTHONUNBUFFERED=1
if not defined PYTHONIOENCODING set PYTHONIOENCODING=utf-8

if not defined SEDA_POSTAL_CODE set SEDA_POSTAL_CODE=01001-001
if not defined SEDA_TIMEOUT set SEDA_TIMEOUT=25
if not defined SEDA_FETCH_MODE set SEDA_FETCH_MODE=magalu_graphql_first
if not defined SEDA_MAGALU_LISTING_FETCH_MODE set SEDA_MAGALU_LISTING_FETCH_MODE=browser
if not defined SEDA_MAGALU_LISTING_ALLOW_ZENROWS set SEDA_MAGALU_LISTING_ALLOW_ZENROWS=0
if not defined SEDA_ALLOW_ZENROWS set SEDA_ALLOW_ZENROWS=0
if not defined SEDA_MAGALU_LISTING_ZENROWS_DRY_RUN set SEDA_MAGALU_LISTING_ZENROWS_DRY_RUN=0
if not defined SEDA_MAGALU_LISTING_ZENROWS_TIMEOUT set SEDA_MAGALU_LISTING_ZENROWS_TIMEOUT=180
if not defined SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_PROFILES set SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_PROFILES=listing_next_data_js_wait,premium_html,auto_custom_headers
if not defined SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_SLEEP_SECONDS set SEDA_MAGALU_LISTING_ZENROWS_FALLBACK_SLEEP_SECONDS=2
set SEDA_MAGALU_DETAIL_GRAPHQL=1
set SEDA_MAGALU_BROWSER_GRAPHQL=1
set SEDA_MAGALU_REVIEW_GRAPHQL=1
set SEDA_MAGALU_HTML_REQUESTS_FETCH=1
set SEDA_MAGALU_HTML_BROWSER_FALLBACK=0
set SEDA_MAGALU_PDP_NAV_FALLBACK=0
set SEDA_MAGALU_ZENROWS_DETAIL_FALLBACK=0
set SEDA_MAGALU_ZENROWS_PDP_FALLBACK=0
if not defined SEDA_MAGALU_SEARCH_BROWSER_ATTEMPTS set SEDA_MAGALU_SEARCH_BROWSER_ATTEMPTS=1
REM listing payload wait: 10s (was 60s) so slow/failed search pages fail fast
if not defined SEDA_MAGALU_SEARCH_BROWSER_READY_TIMEOUT set SEDA_MAGALU_SEARCH_BROWSER_READY_TIMEOUT=10
if not defined SEDA_MAGALU_SEARCH_BROWSER_HTML_ATTEMPTS set SEDA_MAGALU_SEARCH_BROWSER_HTML_ATTEMPTS=3
if not defined SEDA_MAGALU_SEARCH_BROWSER_POLL_SECONDS set SEDA_MAGALU_SEARCH_BROWSER_POLL_SECONDS=0.5
if not defined SEDA_MAGALU_BROWSER_SEARCH_RECYCLE_ATTEMPTS set SEDA_MAGALU_BROWSER_SEARCH_RECYCLE_ATTEMPTS=1
if not defined SEDA_MAGALU_LISTING_FAIL_FAST set SEDA_MAGALU_LISTING_FAIL_FAST=1
if not defined SEDA_MAGALU_SEARCH_RETRIES set SEDA_MAGALU_SEARCH_RETRIES=0
if not defined SEDA_MAGALU_DETAIL_RETRIES set SEDA_MAGALU_DETAIL_RETRIES=0
if not defined SEDA_MAGALU_REVIEW_RETRIES set SEDA_MAGALU_REVIEW_RETRIES=0
if not defined SEDA_MAGALU_REVIEW_INITIAL_SLEEP_SECONDS set SEDA_MAGALU_REVIEW_INITIAL_SLEEP_SECONDS=0
if not defined SEDA_MAGALU_REVIEW_SLEEP_SECONDS set SEDA_MAGALU_REVIEW_SLEEP_SECONDS=0
if not defined SEDA_MAGALU_REVIEW_HTML_MAX_PAGES set SEDA_MAGALU_REVIEW_HTML_MAX_PAGES=10
if not defined SEDA_MAGALU_SHIPPING_BLANK_RETRY set SEDA_MAGALU_SHIPPING_BLANK_RETRY=0
if not defined SEDA_MAGALU_DETAIL_HTML_FALLBACK set SEDA_MAGALU_DETAIL_HTML_FALLBACK=0
if not defined SEDA_MAGALU_DETAIL_403_ABORT_THRESHOLD set SEDA_MAGALU_DETAIL_403_ABORT_THRESHOLD=5
if not defined SEDA_MAGALU_REVIEW_403_ABORT_THRESHOLD set SEDA_MAGALU_REVIEW_403_ABORT_THRESHOLD=5
if not defined SEDA_MAGALU_BROWSER_HTML_ATTEMPTS set SEDA_MAGALU_BROWSER_HTML_ATTEMPTS=1
REM DrissionPage 4.1.1.2 can crash its CDP listener on page navigation
REM (_onDomContentEventFired -> Page.stopLoading -> "Not attached"). With GraphQL
REM page-reuse on, the browser stays on one warm page and only navigates when it
REM recycles -- so disable count-based recycling and stretch the age limit to make
REM navigations (and the crash) rare. GraphQL timeout lowered so the rare crash
REM self-recovers fast instead of stalling on 60s hangs.
if not defined SEDA_MAGALU_BROWSER_MAX_USES set SEDA_MAGALU_BROWSER_MAX_USES=0
if not defined SEDA_MAGALU_BROWSER_MAX_AGE_SECONDS set SEDA_MAGALU_BROWSER_MAX_AGE_SECONDS=3600
if not defined SEDA_MAGALU_BROWSER_GRAPHQL_TIMEOUT set SEDA_MAGALU_BROWSER_GRAPHQL_TIMEOUT=25
if not defined SEDA_MAGALU_BROWSER_RESTART_SLEEP_SECONDS set SEDA_MAGALU_BROWSER_RESTART_SLEEP_SECONDS=2
if not defined SEDA_MAGALU_BROWSER_CLOSE_ON_EXIT set SEDA_MAGALU_BROWSER_CLOSE_ON_EXIT=1
set SEDA_MAGALU_SEARCH_FALLBACK_PAGE_SIZES=

call :log "[SEDA] log file: %SEDA_RUN_LOG_FILE%"
call :log "[SEDA] Magalu %SEDA_LINE% full run started"
call python -m seda.magalu.magalu_orchestrator --product-line %SEDA_LINE% --all
if errorlevel 1 goto :failed

call :log "[SEDA] Magalu %SEDA_LINE% full run completed"
exit /b 0

:log
echo %~1
>> "%SEDA_RUN_LOG_FILE%" echo %~1
exit /b 0

:failed
call :log "[SEDA] Magalu %SEDA_LINE% full run failed"
exit /b 1
